spring:
    application:
        name: apiGateway
    cloud:
        gateway:
            routes:
                - id: patient-service-route
                  uri: http://localhost:4000
                  predicates:
                    - Path=/api/patients/**
                  filters:
                    - StripPrefix=1

                - id: api-docs-route
                  uri: http://localhost:4000
                  predicates:
                    - Path=/api-docs
                  filters:
                    - RewritePath=/api-docs, v3/api-docs
server:
    port: 8022