spring:
  application:
    name: patientService
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/patientManagement}
    username: ${DATABASE_USERNAME:postgres} #postgres
    password: ${DATABASE_PASSWORD:password} #password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
  kafka:
    bootstrap-servers:
      - localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
server:
  port: 4000

